/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  AdvancedSheetHandler as AdvancedSheetHandler
} from './components/advanced-sheet-handler/advanced-sheet-handler';

declare global {
  interface HTMLAdvancedSheetHandlerElement extends AdvancedSheetHandler, HTMLStencilElement {
  }
  var HTMLAdvancedSheetHandlerElement: {
    prototype: HTMLAdvancedSheetHandlerElement;
    new (): HTMLAdvancedSheetHandlerElement;
  };
  interface HTMLElementTagNameMap {
    "advanced-sheet-handler": HTMLAdvancedSheetHandlerElement;
  }
  interface ElementTagNameMap {
    "advanced-sheet-handler": HTMLAdvancedSheetHandlerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "advanced-sheet-handler": JSXElements.AdvancedSheetHandlerAttributes;
    }
  }
  namespace JSXElements {
    export interface AdvancedSheetHandlerAttributes extends HTMLAttributes {
      max_char?: number;
      max_window?: number;
      nglview?: boolean;
      pdbFile?: string;
    }
  }
}


import {
  AdvancedSheet as AdvancedSheet
} from './components/advanced-sheet/advanced-sheet';

declare global {
  interface HTMLAdvancedSheetElement extends AdvancedSheet, HTMLStencilElement {
  }
  var HTMLAdvancedSheetElement: {
    prototype: HTMLAdvancedSheetElement;
    new (): HTMLAdvancedSheetElement;
  };
  interface HTMLElementTagNameMap {
    "advanced-sheet": HTMLAdvancedSheetElement;
  }
  interface ElementTagNameMap {
    "advanced-sheet": HTMLAdvancedSheetElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "advanced-sheet": JSXElements.AdvancedSheetAttributes;
    }
  }
  namespace JSXElements {
    export interface AdvancedSheetAttributes extends HTMLAttributes {
      data?: object;
      max_char?: any;
      pdbFile?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
